apiVersion: v1
kind: Service
metadata:
  name: bedrock-server
spec:
  selector:
    app: bedrock-server
  type: NodePort
  ports:
    - name: mc-port
      protocol: UDP
      port: 19132
      targetPort: 19132
    - name: mc-port-2
      protocol: UDP
      port: 19133
      targetPort: 19133
    - name: web
      protocol: TCP
      port: 50000
      targetPort: 50000
