apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock-server
  template:
    metadata:
      labels:
        app: bedrock-server
    spec:
      containers:
        - name: bedrock-server
          image: bedrock-server:latest
          ports:
            - containerPort: 19132
              protocol: UDP
            - containerPort: 19133
              protocol: UDP
            - containerPort: 50000
              protocol: TCP
          volumeMounts:
            - name: bedrock-data
              mountPath: /bedrock
          livenessProbe:
            httpGet:
              path: /health
              port: 50000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: bedrock-data
          persistentVolumeClaim:
            claimName: bedrock-data-pvc
